### ISSUE TITLE
Is processing of storyboard elements prepared?

### ISSUE THREAD

**Issue by arauschert** [RA-Consulting-GmbH/openscenario.api.test#64]
When a scenario is executed, then a scenario runtime needs to change the states of the storyboard elements (standby/running/completed) as written in the user guide of OSC 1.0. The storyboard elements, which are instantiated by the c++ loader are already derived from IStoryboardElement. But they don´t have a member "StoryboardElementState" (since IStoryboardElement is only an interface used in the StoryboardElementStateCondition to get the reference to a storyboard element and not an implementation class).  

So the question would be how the OSC API architecture assumes the usage of the storyboard elements in the scenario for the runtime?  

Does the scenario engine need to make a copy of the storyboard with it´s own classes that contain a member for the storyboard element state or is there anything prepared which I didn´t see?

**Comment by ahege** [comment]
First we start with the format, we see runtime behavior in the next step. If so, the aspects should be clearly separated because the runtime behavior, e.g. for checkers or editors, of course initially plays no role or only plays a subordinate role.

Now comes the good part:
With addAdapter, functionality can be added to every object in our library at runtime, which can be implemented according to the user without loosing the system boundaries of the library.

For example:
A ConditionEvaluator class (which you define yourself in the engine) can be added to an object of the condition type:

conditionObject-> addAdapter (“conditionEvaluator”, new ConditionEvaluator (conditionObject, connectionToSimulation));

Then you can evaluate with the attached adapter at runtime:

bool conditionValue = ((ConditionEvaluator) conditionObject.getAdapter (“conditionEvaluator“)) -> evaluate ();

The same with the StoryboardElement.

You can attach a StoryRuntimeState class that you have defined to the StoryElement interface.

storyElementObject-> addAdapter ("state", new StoryElementState (storyElementObject));

Then at runtime (STANDBY_STATE can be defined as an enum in the engine)

((StoryElementState) storyElementObject.getAdapter (“state“)) -> setState (STANDBY_STATE);
Or
((StoryElementState) storyElementObject.getAdapter (“state“)) -> getState ();

The execution can be mapped with the command pattern.

action-> addAdapter ("executor", new ActionExecutor (action, connectionToSimulation));

and then

((ActionExecutor )action->getAdapter(„executor“))->execute();

**Comment by ahege** [comment]
It seems that was clarified with some personal communication. (The above comment is a translation of the emal content I wrote @arauschert at that time. I will close the issue. @arauschert  fell free to reopen when needed.
